// <auto-generated />
using System;
using LetsMeatAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LetsMeatAPI.Migrations
{
    [DbContext(typeof(LMDbContext))]
    [Migration("20201219094406_InvitationTimestamp")]
    partial class InvitationTimestamp
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("CustomLocationEvent", b =>
                {
                    b.Property<Guid>("CandidateCustomLocationsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventsWithMeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CandidateCustomLocationsId", "EventsWithMeId");

                    b.HasIndex("EventsWithMeId");

                    b.ToTable("CustomLocationEvent");
                });

            modelBuilder.Entity("EventGoogleMapsLocation", b =>
                {
                    b.Property<string>("CandidateGoogleMapsLocationsId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("EventsWithMeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CandidateGoogleMapsLocationsId", "EventsWithMeId");

                    b.HasIndex("EventsWithMeId");

                    b.ToTable("EventGoogleMapsLocation");
                });

            modelBuilder.Entity("GroupUser", b =>
                {
                    b.Property<Guid>("GroupsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UsersId")
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("GroupsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("GroupUser");
                });

            modelBuilder.Entity("LetsMeatAPI.Models.CustomLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("CreatedForId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedForId");

                    b.ToTable("CustomLocations");
                });

            modelBuilder.Entity("LetsMeatAPI.Models.Debt", b =>
                {
                    b.Property<string>("FromId")
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ToId")
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("FromId", "ToId", "GroupId");

                    b.HasIndex("GroupId");

                    b.HasIndex("ToId");

                    b.ToTable("Debts");
                });

            modelBuilder.Entity("LetsMeatAPI.Models.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CandidateTimes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("GroupId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("LetsMeatAPI.Models.GoogleMapsLocation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Latitude")
                        .HasColumnType("real");

                    b.Property<float>("Longitude")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GoogleMapsLocations");
                });

            modelBuilder.Entity("LetsMeatAPI.Models.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("LetsMeatAPI.Models.Invitation", b =>
                {
                    b.Property<string>("ToId")
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FromId")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("Sent")
                        .HasColumnType("datetime2");

                    b.HasKey("ToId", "GroupId");

                    b.HasIndex("FromId");

                    b.HasIndex("GroupId");

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("LetsMeatAPI.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prefs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LetsMeatAPI.Models.Vote", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Order")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EventId", "UserId");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("CustomLocationEvent", b =>
                {
                    b.HasOne("LetsMeatAPI.Models.CustomLocation", null)
                        .WithMany()
                        .HasForeignKey("CandidateCustomLocationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LetsMeatAPI.Models.Event", null)
                        .WithMany()
                        .HasForeignKey("EventsWithMeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventGoogleMapsLocation", b =>
                {
                    b.HasOne("LetsMeatAPI.Models.GoogleMapsLocation", null)
                        .WithMany()
                        .HasForeignKey("CandidateGoogleMapsLocationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LetsMeatAPI.Models.Event", null)
                        .WithMany()
                        .HasForeignKey("EventsWithMeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GroupUser", b =>
                {
                    b.HasOne("LetsMeatAPI.Models.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LetsMeatAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LetsMeatAPI.Models.CustomLocation", b =>
                {
                    b.HasOne("LetsMeatAPI.Models.Group", "CreatedFor")
                        .WithMany("CustomLocations")
                        .HasForeignKey("CreatedForId")
                        .IsRequired();

                    b.Navigation("CreatedFor");
                });

            modelBuilder.Entity("LetsMeatAPI.Models.Debt", b =>
                {
                    b.HasOne("LetsMeatAPI.Models.User", "From")
                        .WithMany("DebtsForOthers")
                        .HasForeignKey("FromId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LetsMeatAPI.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LetsMeatAPI.Models.User", "To")
                        .WithMany("DebtsForMe")
                        .HasForeignKey("ToId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("From");

                    b.Navigation("Group");

                    b.Navigation("To");
                });

            modelBuilder.Entity("LetsMeatAPI.Models.Event", b =>
                {
                    b.HasOne("LetsMeatAPI.Models.User", "Creator")
                        .WithMany("CreatedEvents")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LetsMeatAPI.Models.Group", "Group")
                        .WithMany("Events")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("LetsMeatAPI.Models.Group", b =>
                {
                    b.HasOne("LetsMeatAPI.Models.User", "Owner")
                        .WithMany("OwnedGroups")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("LetsMeatAPI.Models.Invitation", b =>
                {
                    b.HasOne("LetsMeatAPI.Models.User", "From")
                        .WithMany()
                        .HasForeignKey("FromId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LetsMeatAPI.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LetsMeatAPI.Models.User", "To")
                        .WithMany("Invitations")
                        .HasForeignKey("ToId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("From");

                    b.Navigation("Group");

                    b.Navigation("To");
                });

            modelBuilder.Entity("LetsMeatAPI.Models.Vote", b =>
                {
                    b.HasOne("LetsMeatAPI.Models.Event", null)
                        .WithMany("Votes")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LetsMeatAPI.Models.Event", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("LetsMeatAPI.Models.Group", b =>
                {
                    b.Navigation("CustomLocations");

                    b.Navigation("Events");
                });

            modelBuilder.Entity("LetsMeatAPI.Models.User", b =>
                {
                    b.Navigation("CreatedEvents");

                    b.Navigation("DebtsForMe");

                    b.Navigation("DebtsForOthers");

                    b.Navigation("Invitations");

                    b.Navigation("OwnedGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
